name: Bug Report
description: Report a bug or unexpected behavior in Python IPAM
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug!

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: When I try to...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: I expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Instead...
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Low - Minor issue or cosmetic problem
        - Medium - Feature is impaired but workaround exists
        - High - Feature is broken, no workaround
        - Critical - Application crash or data loss
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Tell us about your environment
      value: |
        - Python IPAM Version:
        - Deployment Method: [Docker/Native Python]
        - Python Version:
        - Operating System:
        - Browser (if UI bug):
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs and Error Messages
      description: Include relevant logs or error messages
      placeholder: Paste logs here...
      render: shell
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about the problem (screenshots, configuration, etc.)
      placeholder: Additional information...
    validations:
      required: false
