name: PR Image Cleanup

on:
  pull_request:
    types: [closed]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  delete-pr-image:
    name: Delete PR Container Image
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Delete PR image from GHCR
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          TAG="pr-${PR_NUMBER}"

          echo "Attempting to delete image tag: ${TAG}"

          # Get package version ID for the PR tag
          VERSION_ID=$(gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "/users/${{ github.repository_owner }}/packages/container/${{ github.event.repository.name }}/versions" \
            --jq ".[] | select(.metadata.container.tags[] | contains(\"${TAG}\")) | .id" || true)

          if [ -n "$VERSION_ID" ]; then
            echo "Found version ID: ${VERSION_ID}"
            gh api \
              --method DELETE \
              -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              "/users/${{ github.repository_owner }}/packages/container/${{ github.event.repository.name }}/versions/${VERSION_ID}"
            echo "Successfully deleted PR image tag: ${TAG}"
          else
            echo "No image found for tag: ${TAG}"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
